# Generated by Django 4.2 on 2025-10-15 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Swipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_no', models.CharField(default='USER1', max_length=50)),
                ('reader_name', models.CharField(choices=[('Main Door - IN', 'Main Door - IN'), ('Main Door - OUT', 'Main Door - OUT')], max_length=32)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
