# Generated by Django 4.2 on 2025-10-15 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swipe',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
